const { Router } = require('express');
const authRoutes = require('./auth.routes');
const userRoutes = require('./user.routes');
const peopleRoutes = require('./people.routes');
const academicRoutes = require('./academic.routes');
const schoolRoutes = require('./school.routes');
const classRoutes = require('./class.routes');
const assignmentRoutes = require('./assignment.routes');
const attendanceRoutes = require('./attendance.routes');
const gradeRoutes = require('./grade.routes');
const messageRoutes = require('./message.routes');
const announcementRoutes = require('./announcement.routes');
const notificationRoutes = require('./notification.routes');
const financeRoutes = require('./finance.routes');
const complianceRoutes = require('./compliance.routes');
const calendarRoutes = require('./calendar.routes');
const resourceRoutes = require('./resource.routes');
const settingsRoutes = require('./settings.routes');
const dashboardRoutes = require('./dashboard.routes');

const router = Router();

router.use('/auth', authRoutes);
router.use('/users', userRoutes);
router.use('/users', peopleRoutes.userRoutes);
router.use('/staff', peopleRoutes.staffRoutes);
router.use('/students', peopleRoutes.studentRoutes);
router.use('/guardians', peopleRoutes.guardianRoutes);
router.use('/enrollments', peopleRoutes.enrollmentRoutes);
router.use('/schools', schoolRoutes);
router.use('/academic-years', academicRoutes.academicYearRoutes);
router.use('/terms', academicRoutes.termRoutes);
router.use('/grade-levels', academicRoutes.gradeLevelRoutes);
router.use('/subjects', academicRoutes.subjectRoutes);
router.use('/class-subjects', academicRoutes.classSubjectRoutes);
router.use('/assessment-types', academicRoutes.assessmentTypeRoutes);
router.use('/grading-scales', academicRoutes.gradingScaleRoutes);
router.use('/classes', classRoutes);
router.use('/assignments', assignmentRoutes);
router.use('/attendance', attendanceRoutes);
router.use('/grades', gradeRoutes);
router.use('/messages', messageRoutes);
router.use('/announcements', announcementRoutes);
router.use('/notifications', notificationRoutes);
router.use('/finance', financeRoutes);
router.use('/consents', complianceRoutes.consentRoutes);
router.use('/audit-logs', complianceRoutes.auditLogRoutes);
router.use('/calendar', calendarRoutes);
router.use('/resources', resourceRoutes);
router.use('/settings', settingsRoutes);
router.use('/dashboard', dashboardRoutes);

module.exports = router;
