#!/usr/bin/env node
/**
 * Generates backend/.env and frontend/.env for local development.
 * Safe dev-only secrets — never use these values in production.
 *
 * Usage (from repo root): node scripts/generate-dev-env.mjs
 */

import { randomBytes } from 'node:crypto';
import { writeFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

function secret(bytes = 32) {
  return randomBytes(bytes).toString('base64url');
}

const backendEnv = `# Auto-generated by scripts/generate-dev-env.mjs — development only
NODE_ENV=development
PORT=5000
API_PREFIX=/api/v1
FRONTEND_URL=http://localhost:5173

DATABASE_URL=postgresql://brightpath:brightpath@127.0.0.1:5433/brightpath?schema=public

JWT_ACCESS_SECRET=${secret()}
JWT_REFRESH_SECRET=${secret()}
JWT_ACCESS_EXPIRES_IN=15m
JWT_REFRESH_EXPIRES_IN=7d

BCRYPT_ROUNDS=12
UPLOAD_DIR=uploads
MAX_FILE_SIZE_MB=10

RATE_LIMIT_WINDOW_MS=900000
RATE_LIMIT_MAX_REQUESTS=1000
LOG_LEVEL=debug
LOG_DIR=logs
`;

const frontendEnv = `# Auto-generated by scripts/generate-dev-env.mjs — development only
# Leave empty to use Vite proxy (recommended): /api/v1 via localhost:5173
VITE_API_BASE=

# Socket.io — same origin as API in dev (Vite does not proxy websockets by default)
VITE_SOCKET_URL=http://localhost:5000
`;

const backendPath = join(root, 'backend', '.env');
const frontendPath = join(root, 'frontend', '.env');

for (const [path, content, label] of [
  [backendPath, backendEnv, 'backend/.env'],
  [frontendPath, frontendEnv, 'frontend/.env'],
]) {
  if (existsSync(path)) {
    console.log(`skip ${label} (already exists)`);
  } else {
    writeFileSync(path, content, 'utf8');
    console.log(`created ${label}`);
  }
}

console.log('\nNext: start Postgres, migrate, seed, then run apps (see LOCAL_SETUP.md).');
